# -*- coding: utf-8 -*-
"""Statistical Tests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2Uw-sUxi6iu-OmeodPQaW5vRTfpMQwS

#**5 Statistical Tests**

## **5.1 Dickey-Fuller-Test**
"""

dickey = sm.tsa.stattools.adfuller(eth.resample("W").mean().close)

print(f'ADF Statistic: {dickey[0]:.2f}')
print(f'p-value: {dickey[1]:.2f}')
print('Critical Values:')
for key, value in dickey[4].items():
        print(f'\t {key}: {value:.3f}')

dickey2 = sm.tsa.stattools.adfuller(eth.resample("W").mean().close_log)

print(f'ADF Statistic: {dickey2[0]:.2f}')
print(f'p-value: {dickey2[1]:.2f}')
print('Critical Values:')
for key, value in dickey2[4].items():
        print(f'\t {key}: {value:.3f}')