# -*- coding: utf-8 -*-
"""Deploy Model into Recent Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2Uw-sUxi6iu-OmeodPQaW5vRTfpMQwS

# **9. Deploy Model into Recent Data**
"""

# Scale before model
scaled_recent = scaler.fit_transform(eth_recent)

# Generate a new dataset out of recent data
X_test2, y_test2 = create_dataset(scaled_recent, 50, -1)



# Evaluate the performance of model on recent data and plot the results
evaluate_model(LSTM_Model, "LSTM Recent", X_test2, y_test2)